//User login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";

//Register user
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

// Create new post
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SERVER_RESPONSE_ERROR =
  "CREATE_POST_SERVER_RESPONSE_ERROR";
export const CREATE_POST_SERVER_RESPONSE_SUCCESS =
  "CREATE_POST_SERVER_RESPONSE_SUCCESS";

// Read posts
export const READ_POST = "READ_POST";
export const READ_POST_SERVER_RESPONSE_ERROR =
  "READ_POST_SERVER_RESPONSE_ERROR";
export const READ_POST_SERVER_RESPONSE_SUCCESS =
  "READ_POST_SERVER_RESPONSE_SUCCESS";

// delete post
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";

// edit post
export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

// chat types
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_USER = "ADD_USER";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const USERS_LIST = "USERS_LIST";
