//user login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";

// create new post
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SERVER_RESPONSE_ERROR =
  "CREATE_POST_SERVER_RESPONSE_ERROR";
export const CREATE_POST_SERVER_RESPONSE_SUCCESS =
  "CREATE_POST_SERVER_RESPONSE_SUCCESS";
