//User login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";

// Create new post
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SERVER_RESPONSE_ERROR =
  "CREATE_POST_SERVER_RESPONSE_ERROR";
export const CREATE_POST_SERVER_RESPONSE_SUCCESS =
  "CREATE_POST_SERVER_RESPONSE_SUCCESS";

// Read posts
export const READ_POST = "READ_POST";
export const READ_POST_SERVER_RESPONSE_ERROR =
  "READ_POST_SERVER_RESPONSE_ERROR";
export const READ_POST_SERVER_RESPONSE_SUCCESS =
  "READ_POST_SERVER_RESPONSE_SUCCESS";

// delete post
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
